version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app_network

  middleware:
    build:
      context: ./mid
    container_name: middleware
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
