version: '3.9'

services:
  backend:
    image: pois0n/ticket-db:latest  # Imagem do Docker Hub para o serviço backend
    container_name: back
    ports:
      - "3000:3000"
    networks:
      - app_network

  middleware:
    image: pois0n/ticket-api:latest  # Imagem do Docker Hub para o serviço middleware
    container_name: middle
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
