name: Docker Deployment

on:


  push:
    branches: [ main ]
    paths:
      - 'back/backend/**'
      - 'back/mid/**'
      - 'front/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      database: ${{ steps.changes.outputs.database }}
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Detect file changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            database:
              - 'back/backend/**'
            backend:
              - 'back/mid/**'
            frontend:
              - 'front/**'

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push database
        if: needs.detect-changes.outputs.database == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./back/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticket-db:latest
      
      - name: Build and push backend
        if: needs.detect-changes.outputs.backend == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./back/mid
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticket-api:latest
      
      - name: Build and push frontend
        if: needs.detect-changes.outputs.frontend == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticket-front:latest
