name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      backend:
        image: pois0n/ticket-db:latest
        ports:
          - 3000:3000

      middleware:
        image: pois0n/ticket-api:latest
        ports:
          - 8000:8000

      frontend:
        image: pois0n/ticket-front:latest
        ports:
          - 5000:5000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies (Front)
        working-directory: ./front
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Install dependencies (Mid)
        working-directory: ./back/mid
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Install dependencies (Back)
        working-directory: ./back/backend
        run: |
          pip install pytest requests

      - name: Wait for services to be ready
        run: |
          echo "Aguardando containers subirem por 90 segundos..."
          sleep 90

      - name: Run Front Unit Tests
        working-directory: ./front
        run: |
          echo "Rodando testes unitários do front..."
          export PYTHONPATH=$PWD
          pytest tests/unit --maxfail=1 -v

      - name: Run Mid & Back Unit Tests
        working-directory: ./back
        run: |
          echo "Rodando testes unitários do mid e back..."
          export PYTHONPATH=$PWD
          pytest tests/unit --maxfail=1 -v

      - name: Run Integration Tests (Front -> Mid)
        working-directory: ./front
        run: |
          echo "Rodando testes de integração Front->Mid..."
          export PYTHONPATH=$PWD
          pytest tests/integration --maxfail=1 -v

      - name: Run Integration Tests (Mid -> Back)
        working-directory: ./back
        run: |
          echo "Rodando testes de integração Mid->Back..."
          export PYTHONPATH=$PWD
          pytest tests/integration --maxfail=1 -v
