name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      backend:
        image: pois0n/ticket-db:latest
        ports:
          - 3000:3000

      middleware:
        image: pois0n/ticket-api:latest
        ports:
          - 8000:8000
        # Caso precise, defina a variável de ambiente:
        # environment:
        #   BACKEND_URL: http://backend:3000

      frontend:
        image: pois0n/ticket-front:latest
        ports:
          - 5000:5000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies (Front)
        working-directory: ./front
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Install dependencies (Mid)
        working-directory: ./back/mid
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Install dependencies (Back)
        working-directory: ./back/backend
        run: |
          pip install pytest requests

      - name: Wait for services to be ready
        run: |
          echo "Aguardando containers subirem por 90 segundos..."
          sleep 90

      # Testes do api.py (backend) usando o container (unit do back)
      - name: Run Back API Endpoint Tests (Unit)
        working-directory: ./back/tests/unit
        run: |
          echo "Rodando testes unitários do backend (api.py) contra o container..."
          pytest test_api.py --maxfail=1 -v

      # Testes unitários do front
      - name: Run Front Unit Tests
        working-directory: ./front
        run: |
          export PYTHONPATH=$PWD
          echo "Rodando testes unitários do front..."
          pytest tests/unit --maxfail=1 -v

      # Testes unitários do mid e back (outros testes unitários)
      - name: Run Mid & Back Unit Tests
        working-directory: ./back
        run: |
          echo "Rodando testes unitários do mid e outros do back..."
          pytest tests/unit --maxfail=1 -v

      # Teste de integração recém-criado (register_and_login_user) no middleware
      - name: Run Integration Test (Register & Login User)
        # Supondo que o teste de integração esteja em ./back/tests/integration/test_register_and_login.py
        working-directory: ./back
        run: |
          export PYTHONPATH=$PWD
          echo "Rodando teste de integração (Register & Login User via middleware)..."
          pytest tests/integration/test_register_and_login.py --maxfail=1 -v
